Backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

Frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

CI/CD:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
