Backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

Frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

CI/CD:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

OpenAPI:
  - changed-files:
    - any-glob-to-any-file: 'openapi/**'
    - any-glob-to-any-file: 'backend/svc/pkg/openapi/**'
    - any-glob-to-any-file: 'frontend/src/api/**'
