services:
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: build/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bakery
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: