services:
  server:
    container_name: yosegaki-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: build/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    container_name: yosegaki-db
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: yosegaki
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    container_name: yosegaki-adminer
    image: adminer
    restart: always
    ports:
      - 6666:8080
  migrate:
    container_name: yosegaki-migate
    volumes:
      - ./migrate:/migrate
    build:
      context: .
      dockerfile: migrate/Dockerfile




volumes:
  db_data: