version: '3'

tasks:
  dev-up:
    cmds:
      - docker compose up -d
  dev-down:
    cmds:
      - docker compose down
  dev-build:
    cmds:
      - docker compose build
  dev-build-nocache:
    cmds:
      - docker compose build --no-cache