version: '3'

tasks:
  docker/dev/up:
    aliases:
      - dev-up
    cmds:
      - docker compose up -d
  docker/dev/down:
    aliases:
      - dev-down
    cmds:
      - docker compose down
  docker/dev/build:
    aliases:
      - dev-build
    cmds:
      - docker compose build
  docker/dev/build/nocache:
    aliases:
      - dev-build-nocache
    cmds:
      - docker compose build --no-cache