// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/health)
	GetApiV1Health(c *gin.Context)

	// (POST /api/v1/login)
	PostApiV1Login(c *gin.Context)

	// (POST /api/v1/message)
	PostApiV1Message(c *gin.Context)

	// (GET /api/v1/messages/{locationId})
	GetApiV1MessagesLocationId(c *gin.Context, locationId string)

	// (POST /api/v1/signup)
	PostApiV1Signup(c *gin.Context)
	// Retrieve a list of locations
	// (GET /api/v1/spot/{spotId}/photo)
	GetApiV1SpotSpotIdPhoto(c *gin.Context, spotId string)
	// Retrieve a list of locations
	// (GET /api/v1/spots)
	GetApiV1Spots(c *gin.Context, params GetApiV1SpotsParams)

	// (GET /api/v1/user/me)
	GetApiV1UserMe(c *gin.Context)

	// (GET /api/v1/user/{userId})
	GetApiV1UserUserId(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiV1Health operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Health(c)
}

// PostApiV1Login operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Login(c)
}

// PostApiV1Message operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Message(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Message(c)
}

// GetApiV1MessagesLocationId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1MessagesLocationId(c *gin.Context) {

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameter("simple", false, "locationId", c.Param("locationId"), &locationId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1MessagesLocationId(c, locationId)
}

// PostApiV1Signup operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Signup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Signup(c)
}

// GetApiV1SpotSpotIdPhoto operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1SpotSpotIdPhoto(c *gin.Context) {

	var err error

	// ------------- Path parameter "spotId" -------------
	var spotId string

	err = runtime.BindStyledParameter("simple", false, "spotId", c.Param("spotId"), &spotId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spotId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1SpotSpotIdPhoto(c, spotId)
}

// GetApiV1Spots operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Spots(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1SpotsParams

	// ------------- Required query parameter "longitude" -------------

	if paramValue := c.Query("longitude"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument longitude is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "longitude", c.Request.URL.Query(), &params.Longitude)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter longitude: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "latitude" -------------

	if paramValue := c.Query("latitude"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument latitude is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "latitude", c.Request.URL.Query(), &params.Latitude)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter latitude: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Spots(c, params)
}

// GetApiV1UserMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UserMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1UserMe(c)
}

// GetApiV1UserUserId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UserUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1UserUserId(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/health", wrapper.GetApiV1Health)
	router.POST(options.BaseURL+"/api/v1/login", wrapper.PostApiV1Login)
	router.POST(options.BaseURL+"/api/v1/message", wrapper.PostApiV1Message)
	router.GET(options.BaseURL+"/api/v1/messages/:locationId", wrapper.GetApiV1MessagesLocationId)
	router.POST(options.BaseURL+"/api/v1/signup", wrapper.PostApiV1Signup)
	router.GET(options.BaseURL+"/api/v1/spot/:spotId/photo", wrapper.GetApiV1SpotSpotIdPhoto)
	router.GET(options.BaseURL+"/api/v1/spots", wrapper.GetApiV1Spots)
	router.GET(options.BaseURL+"/api/v1/user/me", wrapper.GetApiV1UserMe)
	router.GET(options.BaseURL+"/api/v1/user/:userId", wrapper.GetApiV1UserUserId)
}
