// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

// HealthRes defines model for HealthRes.
type HealthRes struct {
	Message string `json:"message"`
}

// SuccessMessageRes defines model for SuccessMessageRes.
type SuccessMessageRes struct {
	Messages []struct {
		// AuthorName Author of the message
		AuthorName *string `json:"author_name,omitempty"`

		// Content Message content
		Content *string `json:"content,omitempty"`

		// Id Message ID
		Id *string `json:"id,omitempty"`

		// Stamps Message stamps
		Stamps *map[string]struct {
			// Count Stamp count
			Count *int `json:"count,omitempty"`

			// IsReacted Check if the user has stamped
			IsReacted *bool `json:"is_reacted,omitempty"`
		} `json:"stamps"`
	} `json:"messages"`
}
