openapi: 3.0.0
info:
  title: Health Check API
  version: "1.0.0"
paths:
  /health:
    get:
      description: health check
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthRes"
components:
  responses:
    SuccessResponse:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SuccessRes"
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
  schemas:
    HealthRes:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: healthy
    SuccessRes:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: ok
    ErrorRes:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: error message
