// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID        string     `gorm:"column:id;type:character(26);primaryKey" json:"id"`
	UserID    string     `gorm:"column:user_id;type:character(26);not null" json:"user_id"`
	SpotID    string     `gorm:"column:spot_id;type:character(26);not null" json:"spot_id"`
	PhotoURL  *string    `gorm:"column:photo_url;type:text" json:"photo_url"`
	Content   *string    `gorm:"column:content;type:text" json:"content"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
