// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameSpot = "spots"

// Spot mapped from table <spots>
type Spot struct {
	ID        string     `gorm:"column:id;type:character(26);primaryKey" json:"id"`
	GmID      string     `gorm:"column:gm_id;type:character varying(255);not null" json:"gm_id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName Spot's table name
func (*Spot) TableName() string {
	return TableNameSpot
}
