// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameStamp = "stamps"

// Stamp mapped from table <stamps>
type Stamp struct {
	Type      string     `gorm:"column:type;type:character varying(255);primaryKey" json:"type"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName Stamp's table name
func (*Stamp) TableName() string {
	return TableNameStamp
}
