// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string     `gorm:"column:id;type:character(26);primaryKey" json:"id"`
	Username     string     `gorm:"column:username;type:character varying(255);not null" json:"username"`
	Email        string     `gorm:"column:email;type:character varying(255);not null" json:"email"`
	PasswordHash string     `gorm:"column:password_hash;type:text;not null" json:"password_hash"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
