name: Auto label PRs with merge conflicts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-for-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'conflict'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
